node(SLAVE) {
    
    stage ('Interrompendo o Container') {
    
        sh 'docker ps > result'
        def result = readFile('result').trim()
        if(result.contains(ARTIFACTID)) {
            sh 'docker stop $ARTIFACTID'
        }
        
        sh 'docker ps -a > result'
        result = readFile('result').trim()
        if(result.contains(ARTIFACTID)) {
            sh 'docker rm $ARTIFACTID'
            sh 'docker rmi $ARTIFACTID:$VERSION'
        }
        
    }        
    
    stage ('Iniciando o Container') {
        sh 'docker login -u serviceacc -p adui3h2k04jDC hom.iwstech.com.br:5000'
        sh 'docker volume create $ARTIFACTID-data'
        sh 'docker run --name $ARTIFACTID -p ' + PORTA + ' -e ENVIRONMENT=' + (SLAVE.equals('master') ? 'prod' : 'hom') + ' -v $ARTIFACTID-data:/var/log/java -d hom.iwstech.com.br:5000/$ARTIFACTID:$VERSION'
    }
    
}