def SLAVE = AMBIENTE.equals('PRODUCAO') ? 'master' : 'hom01'
def BRANCH = AMBIENTE.equals('PRODUCAO') ? 'master' : 'develop'
def pom = null

node() {

    def mvn = tool 'MVN-3.3.9'
    
    stage ('Preparando') {
        git branch: String.valueOf(BRANCH), credentialsId: 'GITLAB', url: '${GITURL}'
        pom = readMavenPom file: 'pom.xml'
    }
    
    stage ('App Build') {
        cleanWs()
        build job: '/servicos/nexus_deploy', parameters: [
            string(name: 'GITURL', value: String.valueOf(GITURL)), 
            string(name: 'GITBRANCH', value: String.valueOf(BRANCH))
        ]
    }

    stage ('Docker Build') {
        build job: '/servicos/docker_build', parameters: [
            string(name: 'GITURL', value: String.valueOf(DOCKERGITURL)), 
            string(name: 'GROUPID', value: String.valueOf(pom.groupId)),
            string(name: 'ARTIFACTID', value: String.valueOf(pom.artifactId)),
            string(name: 'VERSION', value: String.valueOf(pom.version))
        ]
    }
    
    stage ('Docker Run') {
    
        build job: '/servicos/docker_run', parameters: [
            string(name: 'SLAVE', value: String.valueOf(SLAVE)),
            string(name: 'ARTIFACTID', value: String.valueOf(pom.artifactId)),
            string(name: 'VERSION', value: String.valueOf(pom.version)),
            string(name: 'PORTA', value: String.valueOf(PORTA))
        ] 
    }
}

