def STAGE = AMBIENTE
def CFG = CONFIGURACAO.contains('PRODUCAO') ? 'prod' : 'hom'

def pom = null

node(STAGE) {

    stage ('Preparando') {
        cleanWs()
        git branch: String.valueOf(BRANCH), credentialsId: 'GITLAB', url: '${GITURL}'
        pom = readMavenPom file: 'pom.xml'
    }
    
    stage ('App Build') {
        sh 'mvn clean package -DskipTests -U'
    }

    stage ('Docker Build') {
         sh 'docker build --build-arg BINARY_FILE=target/' + pom.artifactId + '.jar -t ' + pom.artifactId + ' .'
    }
    
    stage ('Interrompendo o Container') {
        sh 'docker ps > result'
        def result = readFile('result').trim()
        if(result.contains(pom.artifactId)) {
            sh 'docker stop ' + pom.artifactId
        }
        
        sh 'docker ps -a > result'
        result = readFile('result').trim()
        if(result.contains(pom.artifactId)) {
            sh 'docker rm ' + pom.artifactId
        }
    }        
    
    stage ('Iniciando o Container') {
        sh 'docker volume create ' + pom.artifactId + '-data'
        sh 'docker run --name ' + pom.artifactId + ' -p ' + PORTA + ':8000 -e ENVIRONMENT=' + CFG + ' -v ' + pom.artifactId + '-data:/var/log/java -d ' + pom.artifactId + ':latest'
    }
}

