def SLAVE = AMBIENTE.equals('PRODUCAO') ? 'master' : 'hom01'
def BRANCH = AMBIENTE.equals('PRODUCAO') ? 'master' : 'develop'
def json = null

node(SLAVE) {

    stage ('Preparando') {
        cleanWs()
        git branch: String.valueOf(BRANCH), credentialsId: 'GITLAB', url: '${GITURL}'
        json = readJSON file: 'package.json'
    }

    stage ('App Build') {
        sh 'npm install'
        if(json.version.contains('-SNAPSHOT')) {
            sh 'npm run set-beta'
        }
        sh 'npm run build'
    }

    stage ('Docker Build') {
        sh 'docker build --build-arg BUILD_FOLDER=build -t ' + pom.name + ':' + pom.version + ' .'
    }

    stage ('Interrompendo o Container') {
        sh 'docker ps > result'
        def result = readFile('result').trim()
        if(result.contains(pom.name)) {
            sh 'docker stop ' + pom.name
        }
        
        sh 'docker ps -a > result'
        result = readFile('result').trim()
        if(result.contains(pom.name)) {
            sh 'docker rm ' + pom.name
        }
    }        
    
    stage ('Iniciando o Container') {
        sh 'docker volume create ' + pom.name + '-data'
        sh 'docker run --name ' + pom.name + ' -p ' + PORTA + ' ' + pom.name + ':' + pom.version
    }

}

